baseURL = 'https://mickaumpf.netlify.app/'
languageCode = 'en-us'
title = 'Portfolio'
enableEmoji = true

[menus]
  [[menus.header]]
    name = 'Accueil'
    url = '/'
    weight = 10
  [[menus.header]]
    name = 'Contact'
    url = '/contact'
    weight = 20